//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furry_Community.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_information
    {
        public int it_is_me { get; set; }
        public Nullable<int> help { get; set; }
        public Nullable<int> i_found { get; set; }
        public Nullable<int> i_want_to_shelter_from_the_shelter { get; set; }
        public Nullable<int> i_have_lost { get; set; }
        public int id_all { get; set; }
    
        public virtual help help1 { get; set; }
        public virtual I_found I_found1 { get; set; }
        public virtual I_have_lost I_have_lost1 { get; set; }
        public virtual I_want_to_shelter_from_the_shelter I_want_to_shelter_from_the_shelter1 { get; set; }
        public virtual it_is_me it_is_me1 { get; set; }
    }
}
