//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furry_Community.Models.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Furry_DB : DbContext
    {
        public Furry_DB()
            : base("name=vitya_FurryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<all_information> all_information { get; set; }
        public virtual DbSet<help> help { get; set; }
        public virtual DbSet<how_to_contact_me> how_to_contact_me { get; set; }
        public virtual DbSet<I_found> I_found { get; set; }
        public virtual DbSet<I_have_lost> I_have_lost { get; set; }
        public virtual DbSet<I_want_to_shelter_from_the_shelter> I_want_to_shelter_from_the_shelter { get; set; }
        public virtual DbSet<id_animal> id_animal { get; set; }
        public virtual DbSet<id_shelter> id_shelter { get; set; }
        public virtual DbSet<it_is_me> it_is_me { get; set; }
        public virtual DbSet<reputation> reputation { get; set; }
        public virtual DbSet<role_love_of_animal> role_love_of_animal { get; set; }
        public virtual DbSet<SsylkaNaVideo> SsylkaNaVideo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
