//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furry_Community.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_want_to_shelter_from_the_shelter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_want_to_shelter_from_the_shelter()
        {
            this.all_information = new HashSet<all_information>();
        }
    
        public int ID_help_animal { get; set; }
        public int ID_animal { get; set; }
        public int ID_shelter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<all_information> all_information { get; set; }
        public virtual id_animal id_animal1 { get; set; }
        public virtual id_shelter id_shelter1 { get; set; }
    }
}
