//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furry_Community.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class id_animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public id_animal()
        {
            this.I_want_to_shelter_from_the_shelter = new HashSet<I_want_to_shelter_from_the_shelter>();
        }
    
        public int ID_animal1 { get; set; }
        public Nullable<bool> dogs { get; set; }
        public Nullable<bool> cats { get; set; }
        public Nullable<bool> humsters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_want_to_shelter_from_the_shelter> I_want_to_shelter_from_the_shelter { get; set; }
    }
}
