//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furry_Community.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class id_shelter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public id_shelter()
        {
            this.I_want_to_shelter_from_the_shelter = new HashSet<I_want_to_shelter_from_the_shelter>();
        }
    
        public int ID_shelter1 { get; set; }
        public string Name_of_shelter { get; set; }
        public string Address_of_shelter { get; set; }
        public string Telephone { get; set; }
        public string vid_animals { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_want_to_shelter_from_the_shelter> I_want_to_shelter_from_the_shelter { get; set; }
    }
}
