//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furry_Community.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class reputation_from_the_patrolman
    {
        public int Id { get; set; }
        public Nullable<int> Id_polzovatelya { get; set; }
        public string Comment_of_remark { get; set; }
    }
}
